# Generated by Django 5.2.13 on 2026-05-31 19:19

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_ai_category_document_ai_confidence_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
